estimator:
  - name: average-thalachh
    params: {}


data:
  filepath: "./data/train_classification.csv"

metrics:
  - name: mean absolute error # same as above
    params: {}

export:
  output_dir: ./models

reports:
  dir: ./reports