estimator:
  - name: discretizer
    params:
      bins_per_column:
        thalachh: 4
        age: 5
      strategy: kmeans
  - name: RandomForestModel
    params: {}


data:
  filepath: "./data/train_classification.csv"

metrics:
  - name: f1 score
    params: {}

export:
  output_dir: ./models

reports:
  dir: ./reports