- name: discretizer
  params:
    bins_per_column:
      age: 5
      thalachh: 4
    strategy: kmeans
- name: categorical-encoder
  params:
    force_dense_array: true
    one_hot: true
- name: bagging
  params: {}
